### PR TITLE
fix: checkboxes for nutrition data 

### LINKED ISSUE #7991: Edition mode: sometimes nutrients are not displayed while they exist
### Describe the bug

When coming to "Nutrition facts" section, the values are not displayed.

When clicking on `[ ] Nutrition facts are specified for the product as sold.` checkbox, the values appear.

### To Reproduce

Eg. https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3100080000444
image

Tested on Firefox and Chrome (without any plugin or user script). Nothing special in my browser console...

### PR DESCRIPTION
**Pull request by stephanegigandet**
Should fix #7991

### CODE REVIEW

File: cgi/product_multilingual.pl [hunk 1]
```diff
@@ -1402,6 +1319,114 @@ ($product_ref, $field, $language)
...
+	# Display 2 checkbox to indicate the nutrition values present on the product
+
+	if (not defined $product_ref->{nutrition_data}) {
+		# by default, display the nutrition data entry column for the product as sold
+
+		$product_ref->{nutrition_data} = "on";
+	}
+
+	if (not defined $product_ref->{nutrition_data_prepared}) {
+		# by default, do not display the nutrition data entry column for the prepared product
```
Comment (teolemon) [inline cgi/product_multilingual.pl:1331]: we could try to be smart on dehydrated things

**Review by teolemon — APPROVED** [review]

**Review by CharlesNepote — APPROVED** [review]

File: cgi/product_multilingual.pl (hunk 1 above)
Comment (stephanegigandet) [reply cgi/product_multilingual.pl:1331]: I added something if we have a category that should have nutrition data
