### PR TITLE
fix: Added CORS Support to `/cgi/product_image_unselect.pl` and `/cgi/product_image_crop.pl`

### LINKED ISSUE #11583: CORS error on product image editing endpoints
### What
Getting CORS error when sending a request on `/cgi/product_image_unselect.pl` and `/cgi/product_image_crop.pl` while it donen't occur for `/cgi/product_jqm2.pl`
**Note:** Please also check endpoints for image uploading as well.

### Steps to reproduce the behavior

1. Go to dev console in your browser
2. Paste this in:
```js
const url = 'https://world.openfoodfacts.net/cgi/product_image_unselect.pl'
fetch(url);
```
3. Observe the error
### Expected behavior
It shouldn't give CORS error, just like when this is pasted:
```js
const url = 'https://world.openfoodfacts.net/cgi/product_jqm2.pl'
fetch(url);
```

### Why
- Causing blockage in https://github.com/openfoodfacts/openfoodfacts-explorer/pull/243
This needs to be fixed to carryon with completing product editing in off-explorer.

### Screenshot
Image

### Part of
https://github.com/openfoodfacts/openfoodfacts-explorer/pull/243

### Additional context
CORS error won't be detcted by Postman/curl. Must be done in browser console.

### PR DESCRIPTION
**Pull request by JagjeevanAK**
### What
Added COHRS Support to `/cgi/product_image_unselect.pl` and `/cgi/product_image_crop.pl` as Abbas Has mentioned in his issue this two route were lacking the cohrs support.

### Screenshot

Screenshot 2025-03-12 at 4 00 56 PM

### Related issue(s) and discussion

- Fixes #11583

### CODE REVIEW

File: cgi/product_image_crop.pl [hunk 1]
```diff
@@ -136,7 +136,11 @@
 $log->debug("JSON data output", {data => $data}) if $log->is_debug();
 
 write_cors_headers();
-print header(-type => 'application/json', -charset => 'utf-8') . $data;
+
```
Comment (stephanegigandet) [inline cgi/product_image_crop.pl:139]: So for this one, we were already writing the CORS headers?

Comment (hangy) [reply cgi/product_image_crop.pl:139]: Yes, it's a bit inconsistent in current `main`

Comment (JagjeevanAK) [reply cgi/product_image_crop.pl:139]: I'm also adding a feature that checks if `$code` is undefined. In such cases, it will add the header and send a JSON response with the error. Currently, when `$code` is undefined, the server exits without any response, so handling that with a proper response would be helpful.  
So don't merge the request as of now

**Review by stephanegigandet — APPROVED** [review]
Thank you!
