### PR TITLE
Should fix null dereferencing (issue #1890)

### LINKED ISSUE #1890: Fields with javascript control do not save data
```
product.pl?type=edit&code=5400119526074:2554 Uncaught TypeError: Cannot read property 'categories' of null
    at t.<computed>.<computed>.source (product.pl?type=edit&code=5400119526074:2554)
    at t.<computed>.<computed>._search (jquery-ui.min.js:8)
    at t.<computed>.<computed>._search (jquery-ui.min.js:6)
    at t.<computed>.<computed>.search (jquery-ui.min.js:8)
    at t.<computed>.<computed>.search (jquery-ui.min.js:6)
    at HTMLInputElement.<anonymous> (jquery-ui.min.js:6)
    at Function.each (jquery.js:14)
    at _.fn.init.each (jquery.js:14)
    at _.fn.init.t.fn.<computed> [as autocomplete] (jquery-ui.min.js:6)
    at HTMLInputElement.<anonymous> (product.pl?type=edit&code=5400119526074:2592)
source @ product.pl?type=edit&code=5400119526074:2554
_search @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
search @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery.js:14
each @ jquery.js:14
t.fn.<computed> @ jquery-ui.min.js:6
(anonymous) @ product.pl?type=edit&code=5400119526074:2592
dispatch @ jquery.js:25
q.handle @ jquery.js:24
product.pl?type=edit&code=5400119526074:2554 Uncaught TypeError: Cannot read property 'categories' of null
    at t.<computed>.<computed>.source (product.pl?type=edit&code=5400119526074:2554)
    at t.<computed>.<computed>._search (jquery-ui.min.js:8)
    at t.<computed>.<computed>._search (jquery-ui.min.js:6)
    at t.<computed>.<computed>.search (jquery-ui.min.js:8)
    at t.<computed>.<computed>.search (jquery-ui.min.js:6)
    at HTMLInputElement.<anonymous> (jquery-ui.min.js:6)
    at Function.each (jquery.js:14)
    at _.fn.init.each (jquery.js:14)
    at _.fn.init.t.fn.<computed> [as autocomplete] (jquery-ui.min.js:6)
    at HTMLInputElement.<anonymous> (product.pl?type=edit&code=5400119526074:2592)
source @ product.pl?type=edit&code=5400119526074:2554
_search @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
search @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery.js:14
each @ jquery.js:14
t.fn.<computed> @ jquery-ui.min.js:6
(anonymous) @ product.pl?type=edit&code=5400119526074:2592
dispatch @ jquery.js:25
q.handle @ jquery.js:24
trigger @ jquery.js:25
(anonymous) @ jquery.js:25
each @ jquery.js:14
each @ jquery.js:14
trigger @ jquery.js:25
_.fn.<computed> @ jquery.js:25
(anonymous) @ jquery.tagsinput.min.js:1
dispatch @ jquery.js:25
q.handle @ jquery.js:24
```
@VaiTon I think it does come from your recent feature that suggest past values.

Error line 2554: `const obj = JSON.parse(tag)['categories'];`

### PR DESCRIPTION
**Pull request by VaiTon**
Fixes #1890 

Tested cases:
- [x] After deleting var in localStorage via dev tools.
- [x] After adding tags to other fields

### CODE REVIEW

**Comment by VaiTon** [comment]
Still testing it on local dev docker

File: cgi/product_multilingual.pl [hunk 1]
```diff
@@ -616,9 +616,11 @@ ($$)
 	autocomplete: {
 		source: function(request, response) {
 			if (request.term === "") {
-				const tag = window.localStorage.getItem("po_last_tags");
-				const obj = JSON.parse(tag)['${field}'];
+				let obj = window.localStorage.getItem("po_last_tags");
+				obj = JSON.parse(obj);
 				if (obj == null) return;
+				obj = obj['${field}'];
```
Comment (stephanegigandet) [inline cgi/product_multilingual.pl]: but then obj['${field}'] can be null too right?

Comment (VaiTon) [reply cgi/product_multilingual.pl]: Yep 😆
