### PR TITLE
fix: use normalized ids for untaxonomized ingredients and specific ingredients

### LINKED ISSUE #7063: Match of specific ingredients to ingredients should be canonicalized
### Describe the bug

We parse the origins of ingredients field to store origins of specific ingredients, and then use this info to complement the ingredients extracted from the list of ingredients.

But the matching does not work for ingredients that are not in the taxonomy, as we get ids that are not taxonomized.

e.g.

```
specific_ingredients: [
{
id: "fr:coquillettes",
ingredient: "coquillettes",
origins: "en:italy",
text: "Origine des coquillettes : Italie."
},
{
id: "fr:Comté AOP 4 mois",
ingredient: "Comté AOP 4 mois",
origins: "en:france",
text: "Origine du Comté AOP 4 mois : France."
},
{
id: "fr:jambon supérieur",
ingredient: "jambon supérieur",
origins: "en:france",
text: "Origine du jambon supérieur : France."
},
{
id: "en:white-wine",
ingredient: "Vin blanc",
origins: "en:europe",
text: "Origine du Vin blanc : Europe."
},
{
id: "en:parmesan",
ingredient: "parmesan",
origins: "en:italy",
text: "Origine du parmesan : Italie"
},
{
id: "fr:Origine Crème UHT",
ingredient: "Origine Crème UHT",
origins: "en:france",
text: "Origine Crème UHT : France."
}
],
```

Needs to be matched to:

```
ingredients: [
{
id: "fr:Coquillettes",
percent: 61.6,
percent_estimate: 61.6,
text: "Coquillettes"
},
{
id: "fr:Comté 4 mois",
labels: "en:pdo",
percent: 4.8,
percent_estimate: 4.8,
text: "Comté 4 mois"
},
{
id: "fr:Jambon supérieur",
percent: 14,
percent_estimate: 14,
text: "Jambon supérieur"
},
{
id: "en:white-wine",
origins: "en:europe",
percent: 0.3,
percent_estimate: 0.3,
text: "Vin blanc",
vegan: "maybe",
vegetarian: "yes"
},
{
id: "en:uht-cream",
percent: 7.56,
percent_estimate: 7.56,
text: "Crème UHT",
vegan: "no",
vegetarian: "yes"
},
{
id: "en:fresh-cream",
percent: 4.76,
percent_estimate: 4.76,
text: "Crème fraiche",
vegan: "no",
vegetarian: "yes"
},
{
id: "fr:Parmesan poudre",
percent: 5.6,
percent_estimate: 5.6,
text: "Parmesan poudre"
},
{
id: "fr:Persil plat",
percent: 1.4,
percent_estimate: 1.38,
text: "Persil plat"
}
],
```

### To Reproduce

https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Peaches.+Some+unknown+ingredient%2C+another+unknown+ingredient.%0D%0A%0D%0AOrigin+of+peaches%3A+Spain.+Origin+of+some+unknown+ingredient%3A+France.+origin+of+Another+Unknown+Ingredient%3A+Malta&type=add&action=process&submit=Envoyer

### Expected behavior

Match should be insensitive to case and accents.

### Screenshots

_No response_

### Additional context

_No response_

### Type of device

Other

### Browser version

_No response_

### Number of products impacted

_No response_

### Time per product

_No response_

### PR DESCRIPTION
**Pull request by stephanegigandet**
In the ingredients structure of a product, there is an "id" field, which contains the canonical id of the ingredient. But if the ingredient does not exist in the taxonomy, it was prefixed with the language code but not normalized. So we had entries like "fr:Un ingrédient pas reconnu".

This changes it to a normalized string: "fr:un-ingredient-pas-reconnu".

A result is that is easier to match specific ingredients that are not in the taxonomy: fixes #7063

### CODE REVIEW

File: tests/update_tests_results.sh [hunk 1]
```diff
@@ -9,16 +9,24 @@
...
 perl recipes.t --results expected_test_results/recipes/
 perl export.t --update-expected-results
 perl import_convert_carrefour_france.t --update-expected-results
-perl import_csv_file.t --update-expected-results
+
+cd ..
+
+# Integration tests
+
+perl integration/import_csv_file.t --update-expected-results
```
Comment (alexgarel) [inline tests/update_tests_results.sh:31]: Good catch !

**Review by alexgarel — APPROVED** [review]
LGTM
