### PR TITLE
fix: Email address with space

### LINKED ISSUE #4549: Email address with space
It's possible to create a new user account which email address contains spaces.
Eg. `bibi @fricotin.org`

### PR DESCRIPTION
**Pull request by aadarsh-ram**
### Description

It's possible to create a new user account with an email address that contains spaces.
### Related issue(s) and discussion
- Fixes #4549
- Modified email was not updated to variable after email validation.

### CODE REVIEW

File: lib/ProductOpener/Users.pm [hunk 1]
```diff
@@ -348,6 +348,9 @@ sub check_user_form($$$) {
 	if (not $address) {
 		push @{$errors_ref}, $Lang{error_invalid_email}{$lang};
 	}
+	
+	# If all checks passed, reinitialize with modified email
+	$user_ref->{email} = Email::Valid->address($user_ref->{email});
```
Comment (stephanegigandet) [inline lib/ProductOpener/Users.pm:353]: I think it would be better to do that in a else clause and use the $address which already has the result of Email::Valid->address( -address => $user_ref->{email}, -mxcheck => 1 );

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
Looks good, but we can use the modified email already in $address

File: lib/ProductOpener/Users.pm (hunk 1 above)
Comment (aadarsh-ram) [reply lib/ProductOpener/Users.pm:353]: @stephanegigandet The $address variable becomes a boolean, if a "$@" condition is satisfied. So, I didn't want to disturb that check. Instead, I reinitalized the variable separately.

Comment (aadarsh-ram) [reply lib/ProductOpener/Users.pm]: @stephanegigandet I just realized that now. Really sorry for not noticing it earlier! 
Did a new commit with the else clause and reinitalization with $address variable.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

File: lib/ProductOpener/Users.pm (hunk 1 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Users.pm]: Perfect, thanks!
