### PR TITLE
fix: do not use 'and' translations from Crowdin for ingredient analysis 

### LINKED ISSUE #8794: bug: parsing vitamins from ingredients list
When Croatian is main language. 
When there is "vitamins" followed by a list of vitamin in parenthesis - like this:
vitamini (vitamin C, niacin, pantotenska kiselina, vitamin B6, vitamin B2, vitamin B1, folna kiselina, vitamin B12)

some elements of the list are not correctly parsed.

Example
ingredients list contains: 
vitamini (vitamin C, niacin, pantotenska kiselina, vitamin B6, vitamin B2, vitamin B1, folna kiselina, vitamin B12),

Parsed ingredients is: 
vitamins (vitamin v, tam, n C, vitamin n, vitamin ac,vitamin n, pantotenska kiselina, vitamin B6, vitamin B2, vitamins, vitamin B1, folna k, sel, vitamin na, vitamin B12)

some examples: 
https://hr.openfoodfacts.org/product/3850104258961
https://hr.openfoodfacts.org/product/3831061001043
https://hr.openfoodfacts.org/product/3850334110961
https://hr.openfoodfacts.org/product/5900020019530
https://hr.openfoodfacts.org/product/3850354004257/baktiv-smoothie-sa-%C5%BEitaricama-dukat

### PR DESCRIPTION
**Pull request by stephanegigandet**
Relying on translated strings from Crowdin for translation analysis (e.g. strings like "and") is too fragile, use translations from Ingredients.pm instead.

Fixes #8794

### CODE REVIEW

File: lib/ProductOpener/Ingredients.pm [hunk 1]
```diff
@@ -3382,8 +3382,8 @@ sub normalize_enumeration ($lc, $type, $enumeration) {
 		$trailing_space = " ";
 	}
 
-	my $and = $Lang{_and_}{$lc};
-	#my $enumeration_separators = $obrackets . '|' . $cbrackets . '|\/| \/ | ' . $dashes . ' |' . $commas . ' |' . $commas. '|'  . $Lang{_and_}{$lc};
+	# do not match anything if we don't have a translation for "and"
+	my $and = $and{$lc} || " will not match ";
```
Comment (alexgarel) [inline lib/ProductOpener/Ingredients.pm:3386]: it's a bit confusing to have `$and` named as `%and`… but it's ok.

Also we don't support a lot of languages in `%and` for now… shan't you report current translations in %and ?

`grep -A 3 'msgctxt "_and_"' -r po/common/ |grep msgstr`

**Review by alexgarel — APPROVED** [review]

File: lib/ProductOpener/Ingredients.pm (hunk 1 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Ingredients.pm:3386]: @alexgarel Nice, I never used the -A option :)

Comment (stephanegigandet) [reply lib/ProductOpener/Ingredients.pm:3405]: I added some of the translations, and left out the ones for languages we have poor support (non roman characters mostly)
