### PR TITLE
fix: Do remove empty products

### LINKED ISSUE #11995: Products are not removed by /scripts/remove_empty_products.pl
When I `journalctl -x --since=2025-06-01 -u gen_feeds_daily@off.service`

The logs show:
```
[...]
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 7509546064864
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 3222475960581
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 3360372058878
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 2000000038447
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 3564700610039
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removing product code 5900300036806
Jun 01 02:16:00 off gen_feeds_daily.sh[3147813]: removed 32022 products
```

But none of these products are removed. Eg.
* https://world.openfoodfacts.org/product/7509546064864
* https://world.openfoodfacts.org/product/3222475960581
* https://world.openfoodfacts.org/product/3360372058878

In the json data, nothing can tell there are to be removed. Eg. https://world.openfoodfacts.org/api/v0/product/3360372058878.json

In fact, in the Perl code, the products are not stored (see the following code). Is there a good reason why, or is it just a bug? @stephanegigandet ?

```(perl)
while (my $product_ref = $cursor->next) {

	my $code = $product_ref->{code};

	#print STDERR "updating product $code\n";

	$product_ref = retrieve_product($code);

	if ((defined $product_ref) and ($code ne '')) {

		if (($product_ref->{empty} == 1) and (time() > $product_ref->{last_modified_t} + 86400)) {
			$product_ref->{deleted} = 'on';
			my $comment = "automatic removal of product without information or images";

			print STDERR "removing product code $code\n";
			$removed++;
		}
	}
	else {
		print "product $code : file not found\n";
	}

}

print STDERR "removed $removed products\n";

exit(0);
```

### PR DESCRIPTION
**Pull request by CharlesNepote**
- Fixes #11995

### CODE REVIEW

**Comment by CharlesNepote** [comment]
I have created the user "remove-empty-products". I haven't tested it. @stephanegigandet can you review it?

File: scripts/remove_empty_products.pl [hunk 1]
```diff
@@ -60,7 +63,6 @@
 
 }
 
-print STDERR "removed $removed products\n";
+print STDERR "removed $removed products\n--- End of script $0";
```
Comment (alexgarel) [inline scripts/remove_empty_products.pl]:
```suggestion
print STDERR "removed $removed products\n--- End of script $0\n";
```

File: scripts/remove_empty_products.pl [hunk 2]
```diff
@@ -48,8 +50,9 @@
 
 		if (($product_ref->{empty} == 1) and (time() > $product_ref->{last_modified_t} + 86400)) {
 			$product_ref->{deleted} = 'on';
-			my $comment = "automatic removal of product without information or images";
-
+			my $comment = "remove_empty_products.pl: automatic removal of product without information or images";
```
Comment (CharlesNepote) [inline scripts/remove_empty_products.pl]:
```suggestion
			my $comment = "[$0] automatic removal of product without information or images";
```

**Review by stephanegigandet — APPROVED** [review]
Looks good.
