### PR TITLE
fix: conversion from IU for prepared nutrients 

### LINKED ISSUE #9107: Bad IU conversion in µg for prepared nutrition data
In the following product, 468 UI is converted into 468,000,000 µg, which leads to a data quality error (Nutrition value over 105 - Vitamin a prepared ): https://world.openfoodfacts.org/product/8717896009292/lait-entier-en-poudre-instantane-nestle?rev=45

image

### PR DESCRIPTION
**Pull request by stephanegigandet**
Fixes #9107 + added a test.

### CODE REVIEW

**Review by CharlesNepote — APPROVED** [review]
Sounds good, thanks!

File: lib/ProductOpener/Food.pm [hunk 1]
```diff
@@ -257,8 +257,30 @@ sub default_unit_for_nid ($nid) {
 	}
 }
 
+=head2 assign_nid_modifier_value_and_unit ($product_ref, $nid, $modifier, $value, $unit)
+
+Assign a value with an unit and an optional modifier (< or ~) to a nutrient in the nutriments structure.
```
Comment (benbenben2) [inline lib/ProductOpener/Food.pm:262]:
```suggestion
Assign a value with a unit and an optional modifier (< or ~) to a nutrient in the nutriments structure.
```

**Review by benbenben2 — APPROVED** [review]
LGTM
