### PR TITLE
fix: data quality, false positive, nutrition sum with lower symbol

### LINKED ISSUE #11075: Do not take into account values less than
### What
Error is: `Nutrition-soluble-fiber-plus-insoluble-fiber-greater-than-fiber`

### Steps to reproduce the behaviour
see: https://world.openfoodfacts.org/product/0856651002104/chili-lime-chickpeas-the-good-bean

### Expected behaviour
no error. the algorithm should ignore values with a < sign

### PR DESCRIPTION
**Pull request by benbenben2**
### What
Error is: Nutrition-soluble-fiber-plus-insoluble-fiber-greater-than-fiber should not be raised for 

> Fiber = 5
> insoluble fiber < 1
> soluble fiber = 5

and similar cases.

The PR covers only Fibers, insoluble fiber and soluble fiber.
The PR covers only if symbol is "<"

### Related issue(s) and discussion
- Fixes #11075

### CODE REVIEW

**Review by aleene — COMMENTED** [review]
Great

File: lib/ProductOpener/DataQualityFood.pm [hunk 1]
```diff
@@ -1319,25 +1319,31 @@ sub check_nutrition_data ($product_ref) {
...
+				? $product_ref->{nutriments}{'soluble-fiber_100g'}
+				: 0;
+			my $insoluble_fiber
+				= defined $product_ref->{nutriments}{'insoluble-fiber_100g'}
+				? $product_ref->{nutriments}{'insoluble-fiber_100g'}
+				: 0;
+			my $total_fiber = $soluble_fiber + $insoluble_fiber;
+
+			if ($total_fiber > $product_ref->{nutriments}{fiber_100g} + 0.001) {
+				# ignore if there is "<" symbol (example: <1 + 5 = 5, issue #11075)
```
Comment (stephanegigandet) [inline lib/ProductOpener/DataQualityFood.pm:1334]: I think it would be better to add $soluble_fiber and $insoluble_fiber to $total_fiber only if there isn't a corresponding < modifier.

That way we will trigger the warning if for instance we have 5 g fiber, 10 g insoluble fiber, and < 1g soluble fiber).

**Review by stephanegigandet — APPROVED** [review]
Thanks @benbenben2 !
Approving the PR, but I suggested an improvement.

File: lib/ProductOpener/DataQualityFood.pm (hunk 1 above)
Comment (benbenben2) [reply lib/ProductOpener/DataQualityFood.pm:1334]: Good idea. I applied these changes. If you could review it again, just to be sure. Thanks

Comment (benbenben2) [reply lib/ProductOpener/DataQualityFood.pm]: @stephanegigandet, forgot to push 1 file
