### PR TITLE
fix: make panel ids consistent for ingredients analysis knowledge panels

### LINKED ISSUE #6810: Inconsistant normalization prevents linked knowledge panels from working
### What
vegan/vegetarian/palm oil should already be working, and they don't seem to. It's related to inconsistant normalization.

### Product API output
https://world.openfoodfacts.org/api/v2/product/4006544205006.json?fields=knowledge_panels,attributes
https://world.openfoodfacts.org/api/v2/product/4006544205006.json?fields=knowledge_panels,attributes_groups
"panel_element":{"panel_id":"ingredients_analysis_en:vegan"}

### Attributes API output
https://world.openfoodfacts.org/api/v2/product/4337185341373/k-take-it-veggie-vegan-nuggets?fields=knowledge_panels,attribute_groups
{"attributes":[{"grade":"a","icon_url":"https://static.openfoodfacts.dev/images/attributes/vegan.svg","id":"vegan","match":100,"name":"Vegan","panel_id":"ingredients_analysis_en-vegan","status":"known","title":"Vegan"}

### Who for
Smoothie users
### Part of
- #6808 
- #6493

### PR DESCRIPTION
**Pull request by stephanegigandet**
Fixes #6810

- Panel ids for ingredients analysis properties are now all in this format: ingredients_analysis_[value of the ingredients_analysis_tag]
e.g. ingredients_analysis_en:may-contain-palm-oil
- Attributes link to the same panel ids
- On the website interface, some elements ids include the panel id (to create links). The : character is replaced by -.

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
👍 💚  Thank you very much

File: html/js/product-search.js [hunk 1]
```diff
@@ -379,9 +379,17 @@ function display_product_summary(target, product) {
...
-		if ((attribute.panel_id) && (document.getElementById("panel_" + attribute.panel_id))) {
-			// onclick : open the panel content + reflow to make sur all column content is shown
-			card_html = '<a href="#panel_' + attribute.panel_id + '" onclick="document.getElementById(\'panel_' + attribute.panel_id + '_content\').classList.add(\'active\'); $(document).foundation(\'equalizer\', \'reflow\');"' + card_html + '</a>';
+		if (attribute.panel_id) {
+			// note: on the website, the id for the panel contains : instead of - (e.g. for the ingredients_analysis_en:vegan panel)
+			var panel_element_id = 'panel_' + attribute.panel_id.replace(':', '-');
+			if (document.getElementById(panel_element_id)) {
+				// onclick : open the panel content + reflow to make sur all column content is shown			
+				card_html = '<a href="#' + panel_element_id
+				+ '" onclick="document.getElementById(\'' + panel_element_id + '_content\').classList.add(\'active\'); $(document).foundation(\'equalizer\', \'reflow\');"' + card_html + '</a>';
```
Comment (alexgarel) [inline html/js/product-search.js:388]: I'm not sure that on the new design reflow will work, so this may have to be tested.

File: lib/ProductOpener/Attributes.pm [hunk 2]
```diff
@@ -1405,6 +1404,9 @@ sub compute_attribute_ingredients_analysis($$$) {
 	# the ingredients_analysis taxonomy contains en:palm-oil and not en:contains-palm-oil
 	$analysis_tag =~ s/contains-(.*)$/$1/;
 
+	# Link to the corresponding knowledge panel (the panel id depends on the value of the property)
+	$attribute_ref->{panel_id} = "ingredients_analysis_en:" . $analysis_tag;
```
Comment (alexgarel) [inline lib/ProductOpener/Attributes.pm:1408]: There is also a panel for environmental impact, with id panel_palm_oil
Capture d’écran de 2022-05-24 10-23-17

I don't know which is best to link to…

**Review by alexgarel — APPROVED** [review]
LGTM but I have two comments.

File: lib/ProductOpener/Attributes.pm (hunk 2 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Attributes.pm:1408]: For the panel linked to the palm oil attribute, I think the ingredients analysis panel is the best one, as it explains why we think the product contains or may contain palm oil. One thing we could do is to add the Threatened species panel has a subpanel of the palm oil ingredients analysis panel.

File: html/js/product-search.js (hunk 1 above)
Comment (stephanegigandet) [reply html/js/product-search.js:388]: We currently need the reflow because we use the equalizer function of Foundation (for setting columns of equal height). We don't have this anymore on the new design, so I think it will work. (and we'll be able to remove all the reflow calls)

File: lib/ProductOpener/Attributes.pm (hunk 2 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Attributes.pm:1408]: Filed https://github.com/openfoodfacts/openfoodfacts-server/issues/6820

File: html/js/product-search.js (hunk 1 above)
Comment (alexgarel) [reply html/js/product-search.js:388]: :+1:
