### PR TITLE
fix unitialized values warnings

### LINKED ISSUE #490: Use of uninitialized value $tag in substitution (s///) at /home/off/lib/ProductOpener/Tags.pm line 1955.

### LINKED ISSUE #491: Use of uninitialized value $tag in substitution (s///) at /home/off/lib/ProductOpener/Tags.pm line 1956.

### LINKED ISSUE #492: Use of uninitialized value $tag in pattern match (m//) at /home/off/lib/ProductOpener/Tags.pm line 1959.

### LINKED ISSUE #493: Use of uninitialized value $tag in concatenation (.) or string at /home/off/lib/ProductOpener/Tags.pm line 2007.

### LINKED ISSUE #494: Use of uninitialized value $tag in pattern match (m//) at /home/off/lib/ProductOpener/Tags.pm line 1811.

### PR DESCRIPTION
**Pull request by hangy**
closes #490, closes #491, closes #492, closes #493, closes #494.

### CODE REVIEW

File: lib/ProductOpener/Tags.pm [hunk 1]
```diff
@@ -2059,6 +2059,11 @@ sub canonicalize_taxonomy_tag($$$)
 	my $tag_lc = shift;
 	my $tagtype = shift;
 	my $tag = shift;
+
+	if (not defined $tag) {
```
Comment (stephanegigandet) [inline lib/ProductOpener/Tags.pm]: The changes look good, but when does this happen? We should look at the cases where it happens and fix them, there should not be a reason to call canonicalize_taxonomy_tags with an undefined (or empty) value. I'm worried that we might silently ignore issues elsewhere in the calling code.

**Comment by teolemon** [comment]
@hangy small conflict to solve

File: lib/ProductOpener/Tags.pm [hunk 2]
```diff
@@ -1916,7 +1916,7 @@ sub display_tags_hierarchy_taxonomy($$$) {
 				$img_lc = 'en';
 			}
 			
-			if ($tag =~ /certified|montagna/) {
+			if ((defined $tag) and ($tag =~ /certified|montagna/)) {
 				print STDERR "labels_logo - lc_imgid: $lc_imgid - en_imgid: $en_imgid - canon_tagid: $canon_tagid - img: $img \n";
 			}
```
Comment (stephanegigandet) [inline lib/ProductOpener/Tags.pm]: this was to debug something, it can be completely removed
