### PR TITLE
fix: issue #9876 import spreadsheet template with mandatory fields

### LINKED ISSUE #9876: Generate an import spreadsheet template with mandatory fields only on the producers platform
This issue is part of #9872 , please see the parent issue for context and guidance on how to work on this issue.

In the import template generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl , add a parameter ?fields=mandatory to output only mandatory fields.

### PR DESCRIPTION
**Pull request by himanshisrestha**
### What
This solves the issue #9876 import spreadsheet template with mandatory fields only on the producers platform.
In the import template generated by [https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl](https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl) , added a parameter "?fields=mandatory" to output the excel file with just the mandatory fields.
The issue was solved using param() function of the CGI.pm module. Before this, the code was setup to just find the importance of the header cell and then apply styling accordingly to write the cell. Using the param() function, the passed argument "fields=mandatory" was accepted as a name=value pair which made it easier to decide whether to add the the cell or not.
The change can be seen in the image attached, which returns an excel sheet consisting of 28 columns of mandatory fields only.

### Screenshot

Screenshot 2024-03-18 at 2 43 40 AM

### Related issue(s) and discussion

- Fixes #9876

### CODE REVIEW

File: cgi/generate_sample_import_file.pl [hunk 1]
```diff
@@ -209,8 +189,16 @@
 		}
 
 		# Write cell and comment
+		if($fields_param && $fields_param eq 'mandatory'){
```
Comment (stephanegigandet) [inline cgi/generate_sample_import_file.pl:192]: You can simplify this block by calling "next;" if the script was called with &fields=mandatory is $importance is not "mandatory"'. That way you can leave $worksheet->write($headers_row, $col, $field_ref->{text}, $formats{$importance}); out of the block.

File: lib/ProductOpener/Config_off.pm [hunk 2]
```diff
@@ -180,6 +180,7 @@ use ProductOpener::Config2;
 	stephane
 	tacinte
 	teolemon
+	himanshisrestha
```
Comment (stephanegigandet) [inline lib/ProductOpener/Config_off.pm:183]: This is good for testing, but it should not be included in the PR.

File: .env [hunk 3]
```diff
@@ -65,3 +65,4 @@ LOG_LEVEL_ROOT=TRACE
 LOG_LEVEL_MONGODB=TRACE
 
 BUILD_CACHE_REPO=openfoodfacts/openfoodfacts-build-cache
+CPANMOPTS=--with-develop --with-feature=off_server_dev_tools
```
Comment (stephanegigandet) [inline .env:68]: This should not be included in the PR

**Comment by stephanegigandet** [comment]
Hello @himanshisrestha , thank you for the PR!

I made some comments. In addition, there are some code that was changed that we want to keep:

```
my $description = lang("description");
my $field_id;
my $comment;

$worksheet->set_row(0, 70);
$worksheet->set_column('A:ZZ', 30);
$worksheet->set_column('A:A', 30);
$worksheet->write($description_row, 0, $description, $formats{'description'});
```

This is needed in order to have "Description" translated in other languages.

Could you change the PR so that it contains only the one change for keeping only the mandatory fields? Thanks!

File: lib/ProductOpener/Config_off.pm (hunk 2 above)
Comment (alexgarel) [reply lib/ProductOpener/Config_off.pm:183]: @himanshisrestha, when you test, use stephane or tacinte account to avoid having to change this file.

File: .env (hunk 3 above)
Comment (alexgarel) [reply .env:68]: @himanshisrestha if you use linux or mac, you might use [direnv](https://openfoodfacts.github.io/openfoodfacts-server/dev/how-to-use-direnv/)

**Comment by stephanegigandet** [comment]
Also you  can run "make lint" to automatically format the code.

File: lib/ProductOpener/Config_off.pm (hunk 2 above)
Comment (himanshisrestha) [reply lib/ProductOpener/Config_off.pm:183]: @alexgarel could you please guide me on how to use it

**Comment by himanshisrestha** [comment]
> Also you can run "make lint" to automatically format the code.

Yes, I can. I'm changing all what you mentioned and will update you soon.

File: .env [hunk 4]
```diff
@@ -64,4 +64,4 @@ ELASTICSEARCH_HOSTS=
 LOG_LEVEL_ROOT=TRACE
 LOG_LEVEL_MONGODB=TRACE
 
-BUILD_CACHE_REPO=openfoodfacts/openfoodfacts-build-cache
+BUILD_CACHE_REPO=openfoodfacts/openfoodfacts-build-cache
```
Comment (stephanegigandet) [inline .env:67]: I think this change is unrelated, could you remove it from the PR?

**Review by stephanegigandet — APPROVED** [review]
Looks good to me! (except for the modification in .env file)

Thank you!

**Comment by himanshisrestha** [comment]
Happy to mark my contribution ☺️

File: lib/ProductOpener/Config_off.pm (hunk 2 above)
Comment (alexgarel) [reply lib/ProductOpener/Config_off.pm]: you just go to sign-in -- create account and use the username "stephane"

File: .env (hunk 4 above)
Comment (alexgarel) [reply .env:67]: this is the last empty line which was removed. It sometimes depends on the IDE.
