### PR TITLE
fix: change the reset preference message depend on flavor

### LINKED ISSUE #11228: Open Beauty Facts - Personal Search - "Use default preferences Nutri-Score, Eco-Score and food processing level (NOVA)"
### What
- "Use default preferences Nutri-Score, Eco-Score and food processing level (NOVA)" in the Edit preferences panel
- ex: https://world.openbeautyfacts.org/product/4210201410683/oral-b

Image

### PR DESCRIPTION
**Pull request by RayanGoubet**
### What

Change de reset preference message by an adapted message following the flavor, add a translation for the obf.
New function on product-preferences.js for take the flavor by the current url.

### Related issue(s) and discussion
Related to #11228 
- Fixes #11228

### CODE REVIEW

File: html/js/product-preferences.js [hunk 1]
```diff
@@ -23,6 +23,32 @@ function get_user_product_preferences() {
 	return user_product_preferences;
 }
 
+function getFlavorFromHostname() { // get the flavor by the url
```
Comment (stephanegigandet) [inline html/js/product-preferences.js:26]: This probably works, but I would prefer that we pass the the flavor from the server, so that we don't have to update the JS code when we add new flavors, or change preferences for OPF or OPFF.

See the existing mechanism to pass variables from server to JS here: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Display.pm#L4435

File: html/js/product-preferences.js [hunk 2]
```diff
@@ -23,6 +23,32 @@ function get_user_product_preferences() {
...
+    }
+    
+    return "off"; // default 
+}
+
+var flavor = getFlavorFromHostname();
+
+var reset_message;
+
+if (flavor === "off") { // get the reset message depend on the flavor
```
Comment (stephanegigandet) [inline html/js/product-preferences.js:43]: Instead of having logic like this, I think it would be better to have logic like:
if we have a string with the id reset_preferences_details + product_type (it's better to use the "food" and "beauty" product type instead of the flavors "obf" and "off" as at some point we might merge websites) -> use it
otherwise, if there is no string defined (and not empty), use the default message.

File: html/js/product-preferences.js [hunk 3]
```diff
@@ -23,32 +24,18 @@ function get_user_product_preferences() {
 	return user_product_preferences;
 }
 
-function getFlavorFromHostname() { // get the flavor by the url 
-    var host = window.location.hostname;
+var type_product;
```
Comment (stephanegigandet) [inline html/js/product-preferences.js:27]: Can you rename it to product_type? that's the variable name we use in other parts of the code

File: html/js/product-preferences.js [hunk 4]
```diff
@@ -23,32 +24,18 @@ function get_user_product_preferences() {
...
-    return "off"; // default 
-}
-
-var flavor = getFlavorFromHostname();
-
-var reset_message;
-
-if (flavor === "off") { // get the reset message depend on the flavor
-    reset_message = lang().reset_preferences_details;
+if (flavor === "off") { // get the type of product
```
Comment (stephanegigandet) [inline html/js/product-preferences.js:29]: Instead of passing the flavor to the script, you can directly pass product_type, that way you don't need this logic.

File: po/common/common.pot [hunk 5]
```diff
@@ -7471,6 +7471,22 @@ msgctxt "scan"
...
+
+msgctxt "reset_preferences_details_food"
+msgid "Nutri-Score, Green-Score and food processing level (NOVA)"
+msgstr "Nutri-Score, Green-Score and food processing level (NOVA)"
+
+msgctxt "reset_preferences_details_product"
+msgid "Nutri-Score, Green-Score and food processing level (NOVA)"
+msgstr "Nutri-Score, Green-Score and food processing level (NOVA)"
+
+msgctxt "reset_preferences_details_pet_food"
```
Comment (stephanegigandet) [inline po/common/common.pot:7486]: for pet food, we just have organic and fair trade:

image

File: po/common/common.pot [hunk 6]
```diff
@@ -7479,6 +7479,14 @@ msgctxt "reset_preferences_details_food"
 msgid "Nutri-Score, Green-Score and food processing level (NOVA)"
 msgstr "Nutri-Score, Green-Score and food processing level (NOVA)"
 
+msgctxt "reset_preferences_details_product"
```
Comment (stephanegigandet) [inline po/common/common.pot:7482]: for products, we should just put "Good repairability"

**Review by stephanegigandet — APPROVED** [review]
Thank you!
