### PR TITLE
fix: Automatically unselect images when source image is deleted

### LINKED ISSUE #9793: Automatically unselect images when source image is deleted
### What
- Automatically unselect images when source image is deleted

### PR DESCRIPTION
**Pull request by 4nt0ineB**
### What

Automatically unselect images when source image is deleted

### Related issue(s) and discussion

- Fixes #9793

### CODE REVIEW

File: lib/ProductOpener/Images.pm [hunk 1]
```diff
@@ -1210,10 +1210,17 @@ sub process_image_move ($user_id, $code, $imgids, $move_to, $ownerid) {
 
 				delete $product_ref->{images}{$imgid};
 
+				if ($move_to eq 'trash') {
+					foreach my $related_img (keys %{$product_ref->{images}}) {
+						if ($product_ref->{images}{$related_img}{imgid} eq $imgid) {
+							_process_image_unselect($product_ref, $related_img);
```
Comment (stephanegigandet) [inline lib/ProductOpener/Images.pm:1216]: We want to unselect the image, but we also want to move the selected image files (similar to the source file with the code above) so that they are not visible online any longer as well.

Comment (4nt0ineB) [reply lib/ProductOpener/Images.pm:1219]: ok, I made changes. I use a queue for the images to be moved and If an image has to be unselected because the source is trashed, we add it to the queue to trash it too.

Comment (stephanegigandet) [reply lib/ProductOpener/Images.pm:1219]: Perfect, thank you!

**Review by stephanegigandet — APPROVED** [review]
Thank you!
