### PR TITLE
fix: support for accented language less taxonomy entries + images

### LINKED ISSUE #8212: Add the logo for the Swedish label "A-market"
### Describe the bug

Would be great to add the logo for the A-market label :-) 

Ä-märket 85x90

### To Reproduce

.

### Expected behavior

.

### Screenshots

_No response_

### Additional context

_No response_

### Type of device

Browser

### Browser version

_No response_

### Number of products impacted

_No response_

### Time per product

_No response_

### LINKED ISSUE #8217: Accented xx: language less taxonomy entries need to match strings without accents (e.g. A-market should match xx:Ä-märket)
It is one of the reasons for https://github.com/openfoodfacts/openfoodfacts-server/issues/8212

### PR DESCRIPTION
**Pull request by stephanegigandet**
Fixes #8212
Fixes #8217 

This PR:
- makes the "wildcard language" xx: an unaccented language.
- solves the issue of images for accented taxonomy entries
- adds tests

image

### CODE REVIEW

File: lib/ProductOpener/Tags.pm [hunk 1]
```diff
@@ -686,6 +689,14 @@ sub get_from_cache ($tagtype, @files) {
 	my $tag_www_root = "$www_root/data/taxonomies/$tagtype";
 
 	my $sha1 = Digest::SHA1->new;
+
+	# Add a version string to the taxonomy data
+	# Change this version string if you want to force the taxonomies to be rebuilt
+	# e.g. if the taxonomy building algorithm or configuration has changed
+	# This needs to be done also when the unaccenting parameters for languages set in Config.pm are changed
+
+	$sha1->add("20230316 - made xx: unaccented");
```
Comment (alexgarel) [inline lib/ProductOpener/Tags.pm:698]: Very good idea :-)

**Review by alexgarel — APPROVED** [review]
Perfect !

(ok 90% perfect, as you didn't add tests on `get_tag_image` :wink: )

**Comment by stephanegigandet** [comment]
> (ok 90% perfect, as you didn't add tests on `get_tag_image` wink )

@alexgarel Actually there are 2, and one of them is failing... :-( 

```
# Tags images
is(get_tag_image("en", "labels", "usda-organic"), "/images/lang/en/labels/usda-organic.90x90.svg");
is(get_tag_image("sv", "labels", "sv:ä-märket"), "/images/lang/sv/labels/ä-märket.141x90.png");
```
