### PR TITLE
fix: Added a description line to the import spreadsheet template

### LINKED ISSUE #9879: Add a description line to the import spreadsheet template on the producers platform
This issue is part of https://github.com/openfoodfacts/openfoodfacts-server/issues/9872 , please see the parent issue for context and guidance on how to work on this issue.

We want to add 2 lines to the import template (generated by https://world.pro.openfoodfacts.org/cgi/generate_sample_import_file.pl ):

- a description line that should contain what we currently have in the comments in the header line (and then we can remove the comments)
- an example line

This issue is about adding the description line.

We also need add one first column that just contains "description" and "example" for those 2 lines, and nothing for the the other rows.

See the template proposal: https://docs.google.com/spreadsheets/d/148PWIsSfDRsj8gLJ7cHbQtdapIEscUwX/edit#gid=1221199414 :

We will need to change the importing so that rows that contain something in the first column are skipped.

### PR DESCRIPTION
**Pull request by anaritadauane**
### What

I added a description row to the import spreadsheet template, which now includes all the comments previously located in the header line.

### Screenshot
Screenshot 2024-03-15 at 01 36 53

### Related issue(s) and discussion

- Added a new column on the right to accommodate the Description and Example rows
- Added some width to the Description cell 
- Changed the code that wrote the comments in the header row to write them in the description row 
- Fixes #9879

### CODE REVIEW

**Comment by stephanegigandet** [comment]
@anaritadauane Thank you! For some reason, I get a completely empty spreadsheet when I run your branch, that's weird.

**Comment by anaritadauane** [comment]
> @anaritadauane Thank you! For some reason, I get a completely empty spreadsheet when I run your branch, that's weird.

Really? Let me check

**Comment by stephanegigandet** [comment]
This is what I get in the logs:

```
stephane@stephane-jaguar-NS50-70MU:~/openfoodfacts-server/logs/apache2$ tail -f modperl_error_log 
[..]
[Thu Mar 14 15:58:22.438705 2024] [:error] [pid 22] [Thu Mar 14 15:58:22 2024] -e: Can't locate object method "add_format" via package "workbook" (perhaps you forgot to load "workbook"?) at /opt/product-opener/cgi/generate_sample_import_file.pl line 57.\n

```

There's a missing $

**Comment by stephanegigandet** [comment]
To see errors, you can do ~/openfoodfacts-server/logs/apache2$ tail -f modperl_error_log 
after adding the missing $, there's another error

**Comment by anaritadauane** [comment]
> To see errors, you can do ~/openfoodfacts-server/logs/apache2$ tail -f modperl_error_log after adding the missing $, there's another error

Thanks, I had to fork the repo to pull the request, then copy the changes and add some changes to the unforked repo to make a PR.  I think I needed to go back and test the code to see if there were any errors.
 Going fix the code

**Comment by anaritadauane** [comment]
I have fixed the errors

**Comment by stephanegigandet** [comment]
@anaritadauane It works now, thank you!

This is what I'm getting when I open the file with LibreOffice Calc, is there a way to get more height in Description cells?

image

File: cgi/generate_sample_import_file.pl [hunk 1]
```diff
@@ -59,13 +59,21 @@
...
 my $headers_row = 0;
-my $col = 0;
+my $description_row = 1;
+my $col = 1;
+
+my $field_id;
+my $comment;
+
+$worksheet->set_column('A:A', 30);
+$worksheet->write( $description_row, 0, "Description", $formats{'description'});
```
Comment (stephanegigandet) [inline cgi/generate_sample_import_file.pl:76]: Could you make "Description" a translatable string?

To do that, you need to put lang("description") instead, and then add a stringid "description" in po/common.po and po/en.po (and it would be good to add it in another language so that you can test that you get a different string if you load for instance the site in Spanish: http://es.openfoodfacts.localhost/cgi/generate_sample_import_file.pl

Once you have added / changed a string in po/common.pot / en.po / es.po , you need to run:
make build_lang
make restart

and then you can use lang("description") in the Perl file instead of "Description".

**Comment by stephanegigandet** [comment]
@anaritadauane looks good, thank you! just one request to make the "Description" text translatable

File: cgi/generate_sample_import_file.pl (hunk 1 above)
Comment (anaritadauane) [reply cgi/generate_sample_import_file.pl:76]: Hi @stephanegigandet, 

Yes, I can. But I don't understand if I should add it as stringid or as msid, like in the po/common.po file?

Screenshot 2024-03-15 at 15 10 12

**Comment by anaritadauane** [comment]
> @anaritadauane looks good, thank you! just one request to make the "Description" text translatable

Great! I will add the additional requests.

File: cgi/generate_sample_import_file.pl (hunk 1 above)
Comment (anaritadauane) [reply cgi/generate_sample_import_file.pl]: Followed the instructions and turned "Description" into a translatable string

Comment (stephanegigandet) [reply cgi/generate_sample_import_file.pl]: @anaritadauane Great :)

Can you also add this to en.po so that we have an English translation (English is the default):


```
msgctxt "description"
msgid "Description"
msgstr "Description"
```

File: po/common/es.po [hunk 2]
```diff
@@ -489,6 +489,10 @@ msgctxt "delete_confirmation"
 msgid "This will delete your user details and anonymise all of your contributions. Please re-enter your user name to confirm."
 msgstr "Esto eliminará sus datos de usuario y anonimizará todas sus contribuciones. Vuelva a ingresar su nombre de usuario para confirmar."
 
+msgctxt "description"
+msgid "Descripton"
```
Comment (stephanegigandet) [inline po/common/es.po:493]: small typo, msgid should always be the same as the English translation

```suggestion
msgid "Description"
```

Comment (anaritadauane) [reply po/common/es.po]: sorry 😅, fixed the typo and changed the en.po file

File: cgi/generate_sample_import_file.pl (hunk 1 above)
Comment (anaritadauane) [reply cgi/generate_sample_import_file.pl]: Done

**Comment by stephanegigandet** [comment]
@anaritadauane Could you run "make lint" to fix the formatting? Thank you!

**Comment by anaritadauane** [comment]
> @anaritadauane Could you run "make lint" to fix the formatting? Thank you!

Yes

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you! :)
