### PR TITLE
fix: mongodb _id must be a string

### LINKED ISSUE #4667: Some products in MongoDB are stored with an _id (code) stored as a number instead of a string
> db.products.find({_id : { $type : "long" }}, {code: 1, product_name: 1})
{ "_id" : NumberLong("2210248030310"), "code" : "2210248030310", "product_name" : "Jambon cuit supérieur 3 noix" }
{ "_id" : NumberLong("3220440176203"), "product_name" : "La Laitière Lait d'Amande pépites façon calisson", "code" : "3220440176203" }
{ "_id" : NumberLong("3261830123377"), "code" : "3261830123377", "product_name" : "Lot de 3 Pâté de Foie" }
{ "_id" : NumberLong("3454681006511"), "product_name" : "La fameuse - Pomme Grand-Mère", "code" : "3454681006511" }
{ "_id" : NumberLong("3760228431501"), "code" : "3760228431501", "product_name" : "Crème glacée au lait frais" }
{ "_id" : NumberLong("3760275520791"), "product_name" : "Café moulu", "code" : "3760275520791" }
{ "_id" : NumberLong("4770175481558"), "product_name" : "", "code" : "4770175481558" }
{ "_id" : NumberLong("4770175482692"), "code" : "4770175482692", "product_name" : "" }
{ "_id" : NumberLong("5410827031715"), "code" : "5410827031715", "product_name" : "Saucisson de cheval rouge fumé féculé" }
{ "_id" : NumberLong("5690522007516"), "product_name" : "", "code" : "5690522007516" }
{ "_id" : NumberLong("6191531900922"), "product_name" : "Flocons d'avoine", "code" : "6191531900922" }

I'm not sure how they got created.

### PR DESCRIPTION
**Pull request by stephanegigandet**
There was an issue for barcode changes, the mongodb _id field got a number long type instead of a string.

This:
- fixes the issue so that _id is always stored as a string
- adds a --fix-non-string-ids command to the update_all_products.pl script

Once deployed, we need to:

run ./update_all_products.pl --fix-non-string
issue the MongoDB command indicated at the end of the script run:

products stored in MongoDB with a non string _id have been reloaded from .sto files (if the products still exist) and stored with a string _id.
products with non string ids can now be deleted from MongoDB with this command:
db.products.remove({_id : { $type : "long" }})

Fixes #4667

### CODE REVIEW

File: scripts/update_all_products.pl [hunk 1]
```diff
@@ -1201,10 +1209,11 @@
...
 
 				# Store data to mongodb
-				# Make sure product code is saved as string and not a number
+				# Make sure product _id and code are saved as string and not a number
 				# see bug #1077 - https://github.com/openfoodfacts/openfoodfacts-server/issues/1077
 				# make sure that code is saved as a string, otherwise mongodb saves it as number, and leading 0s are removed
-				$product_ref->{code} = $product_ref->{code} . '';
+				$product_ref->{_id} .= '';
+				$product_ref->{code} .= '';
 				$products_collection->replace_one({"_id" => $product_ref->{_id}}, $product_ref, { upsert => 1 });
```
Comment (alexgarel) [inline scripts/update_all_products.pl:1217]: Should'nt we refactor and have an upsert_product function that ensure this kind of thing ? (Instead of using replace_one directly). This may help avoiding this error and maybe others ?

**Review by alexgarel — APPROVED** [review]
LGTM

File: scripts/update_all_products.pl (hunk 1 above)
Comment (stephanegigandet) [reply scripts/update_all_products.pl:1217]: Good idea. It could be a good issue for open source day. cc @yuktea 
I filed a bug for it: https://github.com/openfoodfacts/openfoodfacts-server/issues/7271
