### PR TITLE
fix: match processing inside ingredients 

### LINKED ISSUE #3625: Unknown Spanish ingredients that should be known
### What

- I'm coming across several ingredients that should be recognized as their 'words' are in both ingredients and in ingredients_processing.
- These are the ones I've found to date - I imagine there is a common root for this so it should provide the information necessary to fix the problem.

```
leche desnatada de vaca
aroma natural de naranja
jugo concentrado de piña
jugo de pasas
```

### Part of
- #5706

### PR DESCRIPTION
**Pull request by stephanegigandet**
fixes #3625

### CODE REVIEW

File: lib/ProductOpener/Ingredients.pm [hunk 1]
```diff
@@ -1452,121 +1452,143 @@ sub parse_processing_from_ingredient ($ingredients_lc, $ingredient) {
...
-					or (
-						(
-							   ($ingredients_lc eq 'de')
-							or ($ingredients_lc eq 'hu')
-							or ($ingredients_lc eq 'ja')
-							or ($ingredients_lc eq 'nl')
-						)
-						and ($new_ingredient =~ /(^($regexp)|($regexp)$)/i)
-					)
+				# Skip the second pass if we already matched a processing ($matching = 1) or if found a known ingredient ($matches = 1)
```
Comment (benbenben2) [inline lib/ProductOpener/Ingredients.pm:1469]:
```suggestion
				# Skip the second pass if we already matched a processing ($matching = 1) or if found a known ingredient ($found_a_known_ingredient = 1)
```

**Review by benbenben2 — APPROVED** [review]
This is great @stephanegigandet!

I made a small comment about comment mentioning variable that you renamed ($matches -> $found_a_known_ingredient)

**Comment by stephanegigandet** [comment]
> I made a small comment about comment mentioning variable that you renamed ($matches -> $found_a_known_ingredient)

Thanks @benbenben2 !
