### PR TITLE
refactor: fix for ingredients count + schema version / API version conversion

### LINKED ISSUE #11610: refactor Ingredients.pm compute_ingredients_tags() to better count ingredients, known and unknown
The logic in compute_ingredients_tags() to count ingredients is buggy, ingredients_n is based on original ingredients, but known_ingredients_n and unknown_ingredients_n are based on the ingredient + its parents in the taxonomy.

e.g. "cane sugar" translates to ingredients_n = 1 and known_ingredients_n  = 4

### PR DESCRIPTION
**Pull request by stephanegigandet**
This PR fixes #11610 by simplifying how we count ingredients and known ingredients.

It removes from products the array ingredients_hierarchy which content is identical to ingredients_tags

As we don't want to break older clients that may use ingredients_hierarchy, we will put it back when the API version is less than 3.2

This PR also introduces a new system to manage schema changes:
- we will add a schema version to each product object
- products schema will be converted as needed (upgraded when reading older product revisions, and downgraded when the requested API version is lower than the current version).

We can also add documentation about the schema changes and the corresponding API version changes.

### CODE REVIEW

File: lib/ProductOpener/Products.pm [hunk 1]
```diff
@@ -124,6 +124,7 @@ BEGIN {
 
 use vars @EXPORT_OK;
 
+use ProductOpener::ProductSchemaChanges qw/$current_schema_version convert_product_schema/;
```
Comment (benbenben2) [inline lib/ProductOpener/Products.pm:127]: you import convert_product_schema but do not use it

```suggestion
use ProductOpener::ProductSchemaChanges qw/$current_schema_version/;
```

**Review by benbenben2 — APPROVED** [review]
LGTM

optionally, you can add headers before the subroutines (it is done for some but not for all).

File: lib/ProductOpener/Products.pm (hunk 1 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Products.pm:127]: I'm thinking to add it in retrieve_product() so that it's always converted to the newest schema

File: docs/api/ref-api-and-product-schema-change-log.md
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:1]: Great, maybe add a link somewhere in index.md ?

File: docs/api/ref-api-and-product-schema-change-log.md [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+## Introduction
+
+The schema of product data in the Open Food Facts database changes over time:
+- We often add new raw data fields (e.g. packaging data), or new computed fields (e.g. health and environmental scores).
+- Occasionally, we refactor some fields to improve how we structure some data (e.g. in the beginning we had a flat list of ingredients, then we added a nested ingredients structure to better represent sub-ingredients).
+
+We consider new fields to be non-breaking changes. When reading product data, make sure that your implementation will ignore new fields and not break.
+
+We consider changed fields to be breaking changes. To maintain backward compatibility, we increase the API version number when there is a breaking change, and we try to serve the old structure when a lower API version is requested by a client.
+
```
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:14]: Maybe add something about the fact that the API might return undocumented fields, you should not rely on them if they are not part of the documentation (but ask on #api channel or opening an issue).

File: docs/api/ref-api-and-product-schema-change-log.md [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+Breaking changes:
+- The ingredients structure is now a nested structure, with sub-ingredients in the "ingredients" field of each ingredient. Previously sub-ingredients were listed at the end of ingredients.
+
+### Product version 997 - API version 1
+
+Breaking changes:
+- For product READ requests, if the product does not exist, we return HTTP status code 404 instead of 200.
+
+### Product version 996 - API version 0
```
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:66]:
```suggestion
### Product version 996 - API version 0

This is considered the initial version.
```

File: docs/api/ref-api-and-product-schema-change-log.md [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+We consider changed fields to be breaking changes. To maintain backward compatibility, we increase the API version number when there is a breaking change, and we try to serve the old structure when a lower API version is requested by a client.
+
+## Product schema version
+
+The product schema version is an integer that is incremented each time there is a change.
+It was introduced in March 2025, with a value of 1001.
+For products updated after March 2025, the product schema version is saved in the schema_version field of the product object.
+For earlier products (or earlier product revisions), the product schema version is 1000 or below. It is not stored in the database, but it can be returned for API requests with an API version lesser than 3.2.
+
+## API version
```
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:22]: Can we make it clear that API 3 is a rapidly evolving API ?

File: docs/api/ref-api-and-product-schema-change-log.md
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:1]: Also I think we must report the API precise version number in api-v3.yml

(Later, it could be great to give people access to documentation to all versions… but this would mean, IMO attaching openapi documentations to releases.

**Review by alexgarel — COMMENTED** [review]
First comments.

Also isn't there anything to change in docs/api/ref ?

File: lib/ProductOpener/ProductSchemaChanges.pm [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+
+	my $from_version = $product_ref->{schema_version} // 999;
+
+	if ($from_version < $to_version) {
+		for (my $schema_version = $from_version; $schema_version < $to_version; $schema_version++) {
+			if (exists $upgrade_functions{$schema_version}) {
+				$upgrade_functions{$schema_version}->($product_ref);
+			}
+		}
+	}
```
Comment (alexgarel) [inline lib/ProductOpener/ProductSchemaChanges.pm:85]:
```suggestion
		# incrementally upgrade schema
		for (my $schema_version = $from_version; $schema_version < $to_version; $schema_version++) {
			if (exists $upgrade_functions{$schema_version}) {
				$upgrade_functions{$schema_version}->($product_ref);
			}
		}
	}
```

File: lib/ProductOpener/ProductSchemaChanges.pm [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+	elsif ($from_version > $to_version) {
+		for (my $schema_version = $from_version; $schema_version > $to_version; $schema_version--) {
```
Comment (alexgarel) [inline lib/ProductOpener/ProductSchemaChanges.pm:87]:
```suggestion
		# incrementally downgrade version
		for (my $schema_version = $from_version; $schema_version > $to_version; $schema_version--) {
```

File: docs/api/ref-api-and-product-schema-change-log.md [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+
+Since 2012, we have used API versions like 0, 1, 2, 3 and 3.1.
+For each of those API version, we have a corresponding product schema version.
+
+When a client makes a request with a specific API version, we do our best to convert the response to the corresponding product schema version.
+
+## Schema version and API version change log
```
Comment (alexgarel) [inline docs/api/ref-api-and-product-schema-change-log.md:29]: Non breaking whit space

```suggestion
## Schema version and API version change log
```

File: tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups-fr.json [hunk 8]
```diff
@@ -328,7 +328,8 @@
             "id" : "labels",
             "name" : "Labels"
          }
-      ]
+      ],
+      "schema_version" : 999
```
Comment (alexgarel) [inline tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups-fr.json:332]: I'm not sure why we have different schema_version.

File: tests/unit/product_schema_changes.t [hunk 9]
```diff
@@ -0,0 +1,55 @@
+#!/usr/bin/perl -w
+
+use Modern::Perl '2017';
+use utf8;
```
Comment (alexgarel) [inline tests/unit/product_schema_changes.t:4]: It's better to use our standards :-)

```suggestion
use ProductOpener::PerlStandards;
```

**Review by alexgarel — APPROVED** [review]
Great PR.

Some comments to look after.

File: docs/api/ref-api-and-product-schema-change-log.md (hunk 2 above)
Comment (stephanegigandet) [reply docs/api/ref-api-and-product-schema-change-log.md:14]: Good idea, doing that.

File: tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups-fr.json (hunk 8 above)
Comment (stephanegigandet) [reply tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups-fr.json:332]: It's an API v3 request, so we return schema_version 999:

```
### Product version 999 - API version 3

Breaking changes:
- All v3 responses (including product READ requests that use the route /api/v3/product/[barcode]) follow the same structure to indicate status (success or failure), errors and warnings.
- The shape, material and recycling properties of each packaging component are localized: we return a hash with an id and a lc_name field, instead of just an id.
```

File: docs/api/ref-api-and-product-schema-change-log.md
Comment (stephanegigandet) [reply docs/api/ref-api-and-product-schema-change-log.md:1]: Added the API version

**Comment by stephanegigandet** [comment]
Added migration and doc for brands taxonomization: https://github.com/openfoodfacts/openfoodfacts-server/pull/11606
