### PR TITLE
fix: prevent default mod_perl error message to be appended

### LINKED ISSUE #7330: mod_perl is appending "Not found" error messages to Product Opener 404 error messages
### Describe the bug

When Product Opener returns a 404, mod_perl appends an error message at the end of the HTML body.

image

### To Reproduce

https://world.openfoodfacts.org/urlthatdoesnotexist

### Expected behavior

No extra error message.

### Screenshots

_No response_

### Additional context

_No response_

### Type of device

Browser

### Browser version

_No response_

### Number of products impacted

_No response_

### Time per product

_No response_

### PR DESCRIPTION
**Pull request by stephanegigandet**
Fixes #7330 .

Also fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/7288 which should help https://github.com/openfoodfacts/smooth-app/issues/2793#issuecomment-1234184480

I renamed display_error() to display_error_and_exit() to make it more clear what the function actually does.

I tried a bunch of different ways to make Apache / mod_perl send back a non 200 status code while not appending a default error body, and the only solution that seems to work is to output the 404 status code and tell Apache it is a 200.

### CODE REVIEW

File: lib/ProductOpener/Display.pm [hunk 1]
```diff
@@ -1325,9 +1336,25 @@ sub display_error($error_message, $status) {
...
+Display an error message using the site template, and terminate the request immediately.
+
+Any code after the call to display_error_and_exit() will not be executed.
+
+=cut
+
+sub display_error_and_exit($error_message, $status) {
+
+	display_error($error_message, $status);
 	exit();
```
Comment (alexgarel) [inline lib/ProductOpener/Display.pm:1354]: Maybe we could set whatever status if we do `exit(Apache2::Const::OK)` ? (or is it the default already ?)

See https://perl.apache.org/docs/2.0/api/ModPerl/Util.html#C_exit_

File: lib/ProductOpener/Display.pm [hunk 2]
```diff
@@ -1316,6 +1318,15 @@ sub display_date_iso($t) {
...
+
+=head2 display_error ( $error_message, $status )
+
+Display an error message using the site template.
+
+The request is not terminated by this function, it will continue to run.
+
+=cut
+
 sub display_error($error_message, $status) {
```
Comment (alexgarel) [inline lib/ProductOpener/Display.pm:1330]: we should take care of the context.
An API request should return a json instead.
I would use a parameter for that, but also have a function is_api_request($request_ref) to determine that.

But maybe this is a separate PR.

File: lib/ProductOpener/Display.pm [hunk 3]
```diff
@@ -7133,14 +7163,13 @@ HTML
...
-		$r->rflush;
-		$r->status($status);
-	}
+
+	my $r = Apache2::RequestUtil->request();
+	$r->rflush;
+	# Setting the status makes mod_perl append a default error to the body
+	# $r->status($status);
+	# Send 200 instead.
+	$r->status(200);
```
Comment (alexgarel) [inline lib/ProductOpener/Display.pm:7172]: For me we should return Apache::Const::OK and propagate this response.

Or maybe in case of $status != 200, we should just use exit() but keep status in request.

**Review by alexgarel — COMMENTED** [review]
Some point of discussion.

Otherwise it's ok to me globally.

File: lib/ProductOpener/Display.pm (hunk 1 above)
Comment (alexgarel) [reply lib/ProductOpener/Display.pm:1354]: sorry, it seems return code is ignored :-D

File: lib/ProductOpener/Display.pm (hunk 3 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Display.pm:7172]: I tried returning Apache::Const::OK but it does not work, Apache still adds a default error body if $r's status is set to anything else than 200.

To test it, I wrote a simple test:

```
use ProductOpener::PerlStandards;

use CGI::Carp qw(fatalsToBrowser);

use Apache2::Const -compile => qw(OK);
use CGI qw/:cgi :form escapeHTML/;


my $status = param("status") || "200";

print header ( -status => $status );

my $body = "Status is set to $status";

binmode(STDOUT, ":encoding(UTF-8)");

print $body;

my $r = Apache2::RequestUtil->request();
$r->rflush;
$r->status($status);

return Apache2::Const::OK;
```

If I set the status to anything than 200, I get the default message added:

image

File: lib/ProductOpener/Display.pm (hunk 2 above)
Comment (stephanegigandet) [reply lib/ProductOpener/Display.pm:1330]: > An API request should return a json instead.

Agreed, but let's make it in another PR, as there may be side effects, and we need to discuss what the right format of that JSON is with the API users.

Comment (alexgarel) [reply lib/ProductOpener/Display.pm:1330]: agree, opened #7365

File: lib/ProductOpener/Display.pm (hunk 3 above)
Comment (alexgarel) [reply lib/ProductOpener/Display.pm:7172]: ok

**Review by alexgarel — APPROVED** [review]
Let's go !
