### PR TITLE
fix: escape issue in additives knowledge panel - remove latex formulas

### LINKED ISSUE #8339: Some additives not shown, malformed knowledge panel for wikipedia abstracts
### Describe the bug

On some pages, we don't show some additives, like E250 in French:

https://fr.openfoodfacts.org/produit/3095758049019/le-torchon-cuit-a-l-etouffee-25-de-sel-fleury-michon

There is an empty panel:

image

### To Reproduce

https://fr.openfoodfacts.org/produit/3095758049019/le-torchon-cuit-a-l-etouffee-25-de-sel-fleury-michon

### Expected behavior

All additives panels shown

### Part of
- #5493

### PR DESCRIPTION
**Pull request by stephanegigandet**
### What
- fixes #8339 (see screenshots in issue)

image

this particular wikipedia abstract is really not relevant to OFF, I would be very much in favor to creating our own additives descriptions.

### Part of
- #5493

### CODE REVIEW

File: lib/ProductOpener/KnowledgePanels.pm [hunk 1]
```diff
@@ -1290,6 +1290,26 @@ sub create_ingredients_analysis_panel ($product_ref, $target_lc, $target_cc, $op
...
+        (                   
+        {                   # match an opening {
+            (?:
+                [^{}]++     # one or more non angle brackets, non backtracking
+                  |
+                (?1)        # found { or }, so recurse to capture group 1
+            )*
+        }                   # match a closing }
+        )                   
+        //xg;
```
Comment (alexgarel) [inline lib/ProductOpener/KnowledgePanels.pm:1308]: So good you used extended format for regexp :heart:

**Review by alexgarel — APPROVED** [review]
:+1:

File: lib/ProductOpener/KnowledgePanels.pm (hunk 1 above)
Comment (stephanegigandet) [reply lib/ProductOpener/KnowledgePanels.pm:1308]: @alexgarel Well I adapted some code I found on Stack Overflow that had this extended format which is indeed quite cool. That's after ChatGPT gave me 3 wrong answers. ;)
