### PR TITLE
fix: add some user info in /cgi/auth.pl body 

### LINKED ISSUE #9910: Return user information in auth.pl if sent with a specific parameter (eg. ?info=json)
We need to know some information like:

* is a user a moderator
* what is it's preferred language

for services like open-prices / nutripatrol / hungergames

It should be quite easy to add this functionality to auth.pl so that if there is a ?info=json parameter, we would return a json with useful information (maybe avoid revealing email for now)

### PR DESCRIPTION
**Pull request by stephanegigandet**
fixes #9910

### CODE REVIEW

File: cgi/auth.pl [hunk 1]
```diff
@@ -55,6 +55,11 @@
 		user => {
 			email => $User{email},
```
Comment (alexgarel) [inline cgi/auth.pl:56]: Shan't we remove it then ?

**Review by alexgarel — APPROVED** [review]
Cool.

File: cgi/auth.pl (hunk 1 above)
Comment (stephanegigandet) [reply cgi/auth.pl:56]: @alexgarel It might be used by the mobile app, I'm not really sure... https://github.com/openfoodfacts/openfoodfacts-server/pull/7455

Comment (stephanegigandet) [reply cgi/auth.pl]: I'm removing the email and asking about it in https://github.com/openfoodfacts/openfoodfacts-dart/issues/893#issuecomment-1999390759
