### PR TITLE
fix: avoid false positive errors for low energy values #7811

### LINKED ISSUE #7811: energy-value-in-kcal-does-not-match-value-in-kj: false positive for low values
### Describe the bug

https://wiki.openfoodfacts.org/Data_quality_issues_which_can%27t_be_fixed#When_energy_values_are_low_.281-10_Kcal.29

When energy values are low (1-10 Kcal?), there are often matching issues between the energy in Kcal and KJ. This often because producers are rounding the values.

Eg. https://world.openfoodfacts.org/product/3502110008459: In this example, 1 Kcal (rounded) => 6 KJ. Because 6 / 4.2 = 1.428, the producer is probably rounding 1.42 to 1.

see also:
* https://world-fr.openfoodfacts.org/produit/3564700737194/jus-de-citron-de-sicile-rustica
* https://world-fr.openfoodfacts.org/produit/4056489009412/jus-de-citron-vert-solevita

### Expected behavior

This should be a warning and not an error.

### PR DESCRIPTION
**Pull request by CharlesNepote**
### Related issue(s) and discussion
- Fixes #7811

### CODE REVIEW

File: lib/ProductOpener/DataQualityFood.pm [hunk 1]
```diff
@@ -682,14 +682,16 @@ sub check_nutrition_data ($product_ref) {
 				push @{$product_ref->{data_quality_errors_tags}}, "en:energy-value-in-kcal-greater-than-in-kj";
 			}
 
-			# check energy in kcal is ~ 4.2 energy in kj
+			# check energy in kcal is ~ 4.2 (+/- 0.5) energy in kj
+			#   +/- 2 to avoid false positives due to rounded values below 2 Kcal.
+			#   Eg. 1.49 Kcal -> 6.26 KJ in reality, can be rounded by the producer to 1 Kcal -> 6 KJ.
```
Comment (CharlesNepote) [inline lib/ProductOpener/DataQualityFood.pm:687]:
```suggestion
			#   Eg. 1.49 Kcal -> 6.26 KJ in reality, can be rounded by the producer to 1 Kcal -> 6 KJ.
			#   Eg. 1.49 Kcal -> 6.26 KJ in reality, can be rounded by the producer to 1 Kcal -> 6 KJ.
			# TODO: add tests in /tests/unit/dataqualityfood.t
```

**Review by alexgarel — APPROVED** [review]
LGTM, thanks !
